VERSION="2.2.1"

ACCOUNTS=[
"GBUQTVHSS5IRRLNY3SNXUPGF7QXBKO4S7FKGA4VRABABWEB7RIPTUZIE",
]

[DOCUMENTATION]
ORG_NAME="BeeCoin"
ORG_URL="https://beecoinapiz.github.io/Beecoin/"
ORG_DESCRIPTION="We are the world's first global project fueled by the carriers of a token represented by a living organism, and this organism consists of one bee, which will be equated to one BEE token."
ORG_LOGO="https://i.ibb.co/VQqcb2B/1.png"
ORG_OFFICIAL_EMAIL="beecoininfo@gmail.com"


[[CURRENCIES]]
code="BEE"
status="live"
display_decimals=2
issuer="GBUQTVHSS5IRRLNY3SNXUPGF7QXBKO4S7FKGA4VRABABWEB7RIPTUZIE"
anchor_asset_type="crypto"
name="BEE Coin"
desc="We are the world's first global project fueled by the carriers of a token represented by a living organism, and this organism consists of one bee, which will be equated to one BEE token."
image="https://i.ibb.co/VQqcb2B/1.png"
fixed_number=50000000000
max_number=50000000000
is_unlimited=false
#BEE Coin Token was issued using the open and inclusive Stellar blockchain network.
